export const SPOTIFY_TOKEN_URL = 'http://localhost:3001/get-spotify-token'
export const SPOTIFY_TRACKS_URL = 'https://api.spotify.com/v1/tracks/?ids='
export const SPOTIFY_FEATURES_URL = 'https://api.spotify.com/v1/audio-features/?ids='
export const AUTH_TOKEN_LOCAL_STORAGE_KEY = 'setlist_auth_token'
export const AUTH_TOKEN_EXPIRES_LOCAL_STORAGE_KEY = 'setlist_auth_token_expires'
