export const ADD_TRACK_TO_SET = 'set/ADD_TRACK_TO_SET'
export const REMOVE_TRACK_FROM_SET = 'set/REMOVE_TRACK_FROM_SET'
export const INSERT_TRACK_TO_SET = 'set/INSERT_TRACK_TO_SET'
export const CHANGE_SET_NAME = 'set/CHANGE_SET_NAME'
export const CHANGE_SET_MAX_DURATION = 'set/CHANGE_SET_MAX_DURATION'
export const ADD_SET = 'set/ADD_SET'
export const REMOVE_SET = 'set/REMOVE_SET'
